.PHONY all:
all:
	gcc -Wall -DPART1 main.c -o diskinfo
	gcc -Wall -DPART2 main.c -o disklist
	gcc -Wall -DPART3 main.c -o diskget
	gcc -Wall -DPART4 main.c -o diskput

.PHONY clean:
clean:
	-rm diskinfo disklist diskget diskput